version: '3.3'
services:
  monitoring-server:
    restart: always
    depends_on:
      - postgresql
      - mysql
      - kafka
    container_name: monitoring-server
    build:
      context: .
    image: monitoring-server:latest
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_MYSQL_URL=jdbc:mysql://mysql:3306/mysql
      - SPRING_DATASOURCE_POSTGRES_URL=jdbc:postgresql://postgresql:5432/postgres
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092

  postgresql:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'

  mysql:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'mysql'

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  prometheus:
    depends_on:
      - monitoring-server
    image: 'prom/prometheus:v2.14.0'
    ports:
      - '9090:9090'
    command: '--config.file=/etc/prometheus/config.yml'
    volumes:
      - './monitoring/prometheus.yml:/etc/prometheus/config.yml'

  grafana:
    depends_on:
      - prometheus
    image: 'grafana/grafana-oss:8.5.25'
    container_name: 'grafana'
    ports:
      - '3000:3000'
    user: 'root'
    links:
      - 'prometheus:prometheus'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_ALERTING_ENABLED=false
      - GF_UNIFIED_ALERTING_ENABLED=true
