spring:
  application:
    name: account-crud
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/mysql
      driverClassName: com.mysql.cj.jdbc.Driver
      username: mysql
      password: password
    postgres:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: password
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always