{
 "title": "Account",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "/account/create(500 Error)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/v1/account/create\",status=\"500\"}"
    }
   ]
  },
  {
   "title": "/account/create(400 Error)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/v1/account/create\",status=\"400\"}"
    }
   ]
  },
  {
   "title": "/account/get(500 Error)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/v1/account/get\", status=\"500\"}"
    }
   ]
  },
  {
   "title": "Postgres Connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgsql_connection{application=\"account-crud\"}"
    }
   ]
  },
  {
   "title": "MySql Connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_connection{application=\"account-crud\"}"
    }
   ]
  },
  {
   "title": "/account/create(200 max response time)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{uri=\"/v1/account/create\",status=\"200\"}"
    }
   ]
  },
  {
   "title": "Kafka Connection( > 0)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_connection_count_total"
    }
   ]
  }
 ]
}