scrape_configs:
  - job_name: 'asyncApi-health'
    scrape_interval: 30s
    metrics_path: '/actuator/health'
    static_configs:
      - targets:
          - 192.168.1.28:8080
  - job_name: 'asyncApi'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.28:8080']